source 'https://github.com/CocoaPods/Specs.git'
## 自己的私有库
source 'git@github.com:Moshimol/JTPrivateLibs.git'

use_frameworks!

platform :ios, '8.0'

target 'JTDomainManagerLib_Example' do
  pod 'JTDomainManagerLib', :path => '../'

  target 'JTDomainManagerLib_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
